# -*- coding: utf-8 -*-
"""EMI calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzoTe_WwOIYTH1x4NV8KyobWVyRb1OU-
"""

def emi_calculator(principal, interest_rate, number_of_years):
  """
  This function calculates the EMI for a loan.

  Args:
    principal: The amount of the loan.
    interest_rate: The annual interest rate in decimal.
    number_of_years: The number of years of the loan.

  Returns:
    The EMI amount.
  """

  monthly_interest_rate = interest_rate / 1200
  number_of_payments = number_of_years * 12

  emi = principal * monthly_interest_rate / (1 - (1 + monthly_interest_rate) ** -number_of_payments)

  return emi


if __name__ == "__main__":
  principal = 100000
  interest_rate = 15
  number_of_years = 20

  emi = emi_calculator(principal, interest_rate, number_of_years)

  print("The EMI is:", emi)